name : pr_safety_checker
on :
    pull_request:
        branches : ["main"]
jobs :
    docker-safety-check:
        runs-on : ubuntu-24.04
        steps:
            - name : checkout
              uses : actions/checkout@v4
            - name : build
              run : docker build -t pr-safety-checker:latest -f sample-app/Dockerfile sample-app/
            - name : trivy check
              uses : aquasecurity/trivy-action@0.35.0
              with :
                format : json
                image-ref: pr-safety-checker:latest
                output : "trivy-results.json"
            - name : post comment
              run : |
                pip install python-dotenv requests
                python3 main.py trivy-results.json
              env :
                GITHUB_TOKEN : ${{secrets.GITHUB_TOKEN}}
                GITHUB_USER : ${{github.actor}}
                ISSUE_NUMBER : ${{github.event.pull_request.number}}





